// Generated by gencpp from file px4_command/AttitudeReference.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_ATTITUDEREFERENCE_H
#define PX4_COMMAND_MESSAGE_ATTITUDEREFERENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace px4_command
{
template <class ContainerAllocator>
struct AttitudeReference_
{
  typedef AttitudeReference_<ContainerAllocator> Type;

  AttitudeReference_()
    : header()
    , throttle_sp()
    , desired_throttle(0.0)
    , desired_attitude()
    , desired_att_q()  {
      throttle_sp.assign(0.0);

      desired_attitude.assign(0.0);
  }
  AttitudeReference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , throttle_sp()
    , desired_throttle(0.0)
    , desired_attitude()
    , desired_att_q(_alloc)  {
  (void)_alloc;
      throttle_sp.assign(0.0);

      desired_attitude.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _throttle_sp_type;
  _throttle_sp_type throttle_sp;

   typedef float _desired_throttle_type;
  _desired_throttle_type desired_throttle;

   typedef boost::array<float, 3>  _desired_attitude_type;
  _desired_attitude_type desired_attitude;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _desired_att_q_type;
  _desired_att_q_type desired_att_q;





  typedef boost::shared_ptr< ::px4_command::AttitudeReference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_command::AttitudeReference_<ContainerAllocator> const> ConstPtr;

}; // struct AttitudeReference_

typedef ::px4_command::AttitudeReference_<std::allocator<void> > AttitudeReference;

typedef boost::shared_ptr< ::px4_command::AttitudeReference > AttitudeReferencePtr;
typedef boost::shared_ptr< ::px4_command::AttitudeReference const> AttitudeReferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_command::AttitudeReference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_command::AttitudeReference_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace px4_command

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'px4_command': ['/home/nvidia/amov_ws/src/px4_command/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::px4_command::AttitudeReference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_command::AttitudeReference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_command::AttitudeReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_command::AttitudeReference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_command::AttitudeReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_command::AttitudeReference_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_command::AttitudeReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e58702438e0c601131590714878133df";
  }

  static const char* value(const ::px4_command::AttitudeReference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe58702438e0c6011ULL;
  static const uint64_t static_value2 = 0x31590714878133dfULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_command::AttitudeReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_command/AttitudeReference";
  }

  static const char* value(const ::px4_command::AttitudeReference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_command::AttitudeReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
## 位置控制器输出： 期望角度、期望角加速度\n\
float32[3] throttle_sp                 ## [0-1] 惯性系下的油门量\n\
float32 desired_throttle               ## [0-1] 机体系z轴\n\
float32[3] desired_attitude            ## [rad]\n\
geometry_msgs/Quaternion desired_att_q ## 四元数\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::px4_command::AttitudeReference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_command::AttitudeReference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.throttle_sp);
      stream.next(m.desired_throttle);
      stream.next(m.desired_attitude);
      stream.next(m.desired_att_q);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttitudeReference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_command::AttitudeReference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_command::AttitudeReference_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "throttle_sp[]" << std::endl;
    for (size_t i = 0; i < v.throttle_sp.size(); ++i)
    {
      s << indent << "  throttle_sp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.throttle_sp[i]);
    }
    s << indent << "desired_throttle: ";
    Printer<float>::stream(s, indent + "  ", v.desired_throttle);
    s << indent << "desired_attitude[]" << std::endl;
    for (size_t i = 0; i < v.desired_attitude.size(); ++i)
    {
      s << indent << "  desired_attitude[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.desired_attitude[i]);
    }
    s << indent << "desired_att_q: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.desired_att_q);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_ATTITUDEREFERENCE_H
