// Generated by gencpp from file px4_command/Topic_for_log.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_TOPIC_FOR_LOG_H
#define PX4_COMMAND_MESSAGE_TOPIC_FOR_LOG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <px4_command/DroneState.h>
#include <px4_command/ControlCommand.h>
#include <px4_command/AttitudeReference.h>
#include <px4_command/ControlOutput.h>

namespace px4_command
{
template <class ContainerAllocator>
struct Topic_for_log_
{
  typedef Topic_for_log_<ContainerAllocator> Type;

  Topic_for_log_()
    : header()
    , time(0.0)
    , Drone_State()
    , Control_Command()
    , Attitude_Reference()
    , Control_Output()  {
    }
  Topic_for_log_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time(0.0)
    , Drone_State(_alloc)
    , Control_Command(_alloc)
    , Attitude_Reference(_alloc)
    , Control_Output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _time_type;
  _time_type time;

   typedef  ::px4_command::DroneState_<ContainerAllocator>  _Drone_State_type;
  _Drone_State_type Drone_State;

   typedef  ::px4_command::ControlCommand_<ContainerAllocator>  _Control_Command_type;
  _Control_Command_type Control_Command;

   typedef  ::px4_command::AttitudeReference_<ContainerAllocator>  _Attitude_Reference_type;
  _Attitude_Reference_type Attitude_Reference;

   typedef  ::px4_command::ControlOutput_<ContainerAllocator>  _Control_Output_type;
  _Control_Output_type Control_Output;





  typedef boost::shared_ptr< ::px4_command::Topic_for_log_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_command::Topic_for_log_<ContainerAllocator> const> ConstPtr;

}; // struct Topic_for_log_

typedef ::px4_command::Topic_for_log_<std::allocator<void> > Topic_for_log;

typedef boost::shared_ptr< ::px4_command::Topic_for_log > Topic_for_logPtr;
typedef boost::shared_ptr< ::px4_command::Topic_for_log const> Topic_for_logConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_command::Topic_for_log_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_command::Topic_for_log_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace px4_command

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'px4_command': ['/home/nvidia/amov_ws/src/px4_command/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::px4_command::Topic_for_log_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_command::Topic_for_log_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_command::Topic_for_log_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_command::Topic_for_log_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_command::Topic_for_log_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_command::Topic_for_log_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_command::Topic_for_log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "946ec97f7fa6aeb302e66bf4d94384f1";
  }

  static const char* value(const ::px4_command::Topic_for_log_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x946ec97f7fa6aeb3ULL;
  static const uint64_t static_value2 = 0x02e66bf4d94384f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_command::Topic_for_log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_command/Topic_for_log";
  }

  static const char* value(const ::px4_command::Topic_for_log_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_command::Topic_for_log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
## log时间\n\
float32 time             ## [s]\n\
\n\
DroneState Drone_State\n\
\n\
ControlCommand Control_Command\n\
\n\
AttitudeReference Attitude_Reference\n\
\n\
ControlOutput Control_Output\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: px4_command/DroneState\n\
std_msgs/Header header\n\
\n\
## 机载电脑是否连接上飞控，true已连接，false则不是\n\
bool connected\n\
## 是否解锁，true为已解锁，false则不是\n\
bool armed\n\
## PX4飞控当前飞行模式\n\
string mode\n\
\n\
## 系统启动时间\n\
float32 time_from_start             ## [s]\n\
\n\
## 无人机状态量：位置、速度、姿态\n\
float32[3] position                 ## [m]\n\
float32[3] velocity                 ## [m/s]\n\
float32[3] attitude                 ## [rad]\n\
geometry_msgs/Quaternion attitude_q ## 四元数\n\
float32[3] attitude_rate            ## [rad/s]\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: px4_command/ControlCommand\n\
std_msgs/Header header\n\
\n\
## 控制命令的编号 防止接收到错误命令， 编号应该逐次递加\n\
uint32 Command_ID\n\
\n\
## 控制命令的模式 \n\
uint8 Mode\n\
# enum Mode 控制模式枚举\n\
uint8 Idle=0\n\
uint8 Takeoff=1\n\
uint8 Move_ENU=2\n\
uint8 Move_Body=3\n\
uint8 Hold=4\n\
uint8 Land=5\n\
uint8 Disarm=6\n\
uint8 PPN_land=7\n\
uint8 Trajectory_Tracking=8\n\
\n\
## 控制参考量 \n\
## 位置参考量：位置、速度、加速度、加加速度、加加加速度\n\
## 角度参考量：偏航角、偏航角速度、偏航角加速度\n\
TrajectoryPoint Reference_State\n\
\n\
================================================================================\n\
MSG: px4_command/TrajectoryPoint\n\
std_msgs/Header header\n\
\n\
## 时刻： 用于轨迹追踪\n\
float32 time_from_start          ## [s]\n\
\n\
# sub_mode 2-bit value:\n\
# 0 for position, 1 for vel, 1st for xy, 2nd for z.\n\
#                   xy position     xy velocity\n\
# z position       	0b00(0)       0b10(2)\n\
# z velocity		0b01(1)       0b11(3)\n\
#\n\
## 控制命令的子模式 \n\
## 可以选择 位置追踪、速度追踪或者其他复合模式，\n\
## 默认为 XYZ位置追踪模式 （sub_mode = 0）； 速度追踪启用时，控制器不考虑位置参考量及位置状态反馈\n\
uint8 Sub_mode\n\
# enum sub_mode\n\
uint8 XYZ_POS = 0\n\
uint8 XY_POS_Z_VEL = 1\n\
uint8 XY_VEL_Z_POS = 2\n\
uint8 XY_VEL_Z_VEL = 3\n\
\n\
## 参考量：位置、速度、加速度、加加速度、加加加速度\n\
float32[3] position_ref          ## [m]\n\
float32[3] velocity_ref          ## [m/s]\n\
float32[3] acceleration_ref      ## [m/s^2]\n\
## float32[3] jerk_ref              ## [m/s^3]\n\
## float32[3] snap_ref              ## [m/s^4]\n\
\n\
## 角度参考量：偏航角、偏航角速度、偏航角加速度\n\
float32 yaw_ref                  ## [rad]\n\
## float32 yaw_rate_ref             ## [rad/s] \n\
## float32 yaw_acceleration_ref     ## [rad/s] \n\
================================================================================\n\
MSG: px4_command/AttitudeReference\n\
std_msgs/Header header\n\
\n\
## 位置控制器输出： 期望角度、期望角加速度\n\
float32[3] throttle_sp                 ## [0-1] 惯性系下的油门量\n\
float32 desired_throttle               ## [0-1] 机体系z轴\n\
float32[3] desired_attitude            ## [rad]\n\
geometry_msgs/Quaternion desired_att_q ## 四元数\n\
\n\
================================================================================\n\
MSG: px4_command/ControlOutput\n\
std_msgs/Header header\n\
\n\
## 位置控制器输出： 期望角度、期望角加速度\n\
float32[3] u_l                 ## [0-1] 惯性系下的油门量\n\
float32[3] u_d                 ## [rad]\n\
\n\
float32[3] NE                  ## [rad]\n\
  \n\
float32[3] Thrust              ## [rad]  \n\
float32[3] Throttle\n\
";
  }

  static const char* value(const ::px4_command::Topic_for_log_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_command::Topic_for_log_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.Drone_State);
      stream.next(m.Control_Command);
      stream.next(m.Attitude_Reference);
      stream.next(m.Control_Output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Topic_for_log_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_command::Topic_for_log_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_command::Topic_for_log_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "Drone_State: ";
    s << std::endl;
    Printer< ::px4_command::DroneState_<ContainerAllocator> >::stream(s, indent + "  ", v.Drone_State);
    s << indent << "Control_Command: ";
    s << std::endl;
    Printer< ::px4_command::ControlCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.Control_Command);
    s << indent << "Attitude_Reference: ";
    s << std::endl;
    Printer< ::px4_command::AttitudeReference_<ContainerAllocator> >::stream(s, indent + "  ", v.Attitude_Reference);
    s << indent << "Control_Output: ";
    s << std::endl;
    Printer< ::px4_command::ControlOutput_<ContainerAllocator> >::stream(s, indent + "  ", v.Control_Output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_TOPIC_FOR_LOG_H
